# Generated by Django 5.2.6 on 2025-09-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogery',
            new_name='Category',
        ),
    ]
